### PR TITLE
Synfig GSoC 2019 application (draft)

### PR DESCRIPTION
**Pull request by reSHARMA**
Please don't merge! This is just to keep the track of application. I could not find a better place for this, any suggestion would be appreciated :)

### CODE REVIEW

**Comment by morevnaproject** [comment]
I suggest to place this to ```docs/gsoc/2019/application.rst```. ^__^

**Comment by reSHARMA** [comment]
We might be filling these answer into a google form, so do we need to merge it?

**Comment by morevnaproject** [comment]
@reSHARMA I would like to keep this document for our records and to simplify submission process in future years.

BTW, I have found our application form from 2012 - https://wiki.synfig.org/Dev:GoogleSoC/ApplicationForm ^__^

We haven't been accepted back then (https://forums.synfig.org/t/gsoc-2012/1795), but it is so fun to see all our ideas got (at least partially) implemented by this moment - https://wiki.synfig.org/Dev:GoogleSoC/Ideas

**Comment by reSHARMA** [comment]
@morevnaproject now it make sense to me :) and it's awesome that we still have 2012 application.
So I'll close this pr and this was never meant to be merged. I've updated application in https://github.com/synfig/synfig-docs-dev/pull/3

**Pull request closed without merging**
