### PR TITLE
Create Setting up QtCreator IDE.rst

### LINKED ISSUE #57: Qt Creator IDE set-up guide for synfig
Qt Creator supports CMake out of the box. It'd be nice if a new page about it is maintained on the doc page.

Maybe break the IDE page into two parts
- Setting up your preferred IDE for Synfig development
    - Netbeans
    - Qt Creator

One could create their own custom kit for Synfig in case they want to modify the CMake generator from the default one provided by Qt Creator (on Linux it's Unix Makefiles).

### PR DESCRIPTION
**Pull request by Keyikedalube**
Fixes #57

### CODE REVIEW

**Comment by ice0** [comment]
Merged. Thank you!

**Comment by Keyikedalube** [comment]
@ice0 Index page isn't updated with a link to this page. Do I have to update `index.rst` like this?
```rst
common/Setting up QtCreator IDE.rst
```

**Comment by ice0** [comment]
@Keyikedalube  yes, it needs to be updated.

**Comment by Keyikedalube** [comment]
@ice0 Thanks! Opened a new issue. Will send PR for that.

**Pull request merged**
