### PR TITLE
start describing the SIF file format

### PR DESCRIPTION
**Pull request by rodolforg**

### CODE REVIEW

**Comment by rodolforg** [comment]
Ugh I didn't link it anywhere :P

**Comment by morevnaproject** [comment]
Awesome! Please make sure to add `common/file_format.rst` to `index.rst`. ^__^

**Comment by rodolforg** [comment]
> Awesome! Please make sure to add `common/file_format.rst` to `index.rst`. ^__^

Ugh Please check if it is in a good position lol. I'll squash it all into a single commit and it'll be ready for merging.

**Comment by rodolforg** [comment]
Hm… And I think I'll reorder some nodes alphabetically (I followed the loadcanvas.cpp …)

**Comment by rodolforg** [comment]
>  I think I'll reorder some nodes alphabetically

Uh… No energy for that now… lol

**Comment by rodolforg** [comment]
Ready for merge. I didn't sort the elements. :P 
@morevnaproject

**Review by ice0 — APPROVED** [review]
Merge as-is, so anyone can improve it later.

**Comment by ice0** [comment]
Merged. Thank you!

**Pull request merged**
