### PR TITLE
GSoC 2019

### PR DESCRIPTION
**Pull request by reSHARMA**
This is just a draft, open for discussions!

Some things to be decided are:
* The open project concept
* I'm mostly worried about the contact part, we need to have a gsoc public mailing list (or anything similar) and one exclusively for mentors.
* A project will have 2 mentor that's my proposal after viewing what is done in other orgs.
* Proposal process

### CODE REVIEW

**Comment by morevnaproject** [comment]
Good start! I suggest to make this document more GSoC-specific. In patrticular, I am proposing place this page to ```docs/gsoc/2019/ideas.rst```.

For reference we can take Blender's ideas page - https://en.blender.org/index.php/Dev:Ref/GoogleSummerOfCode/2018/Ideas

**Comment by morevnaproject** [comment]
> I'm mostly worried about the contact part, we need to have a gsoc public mailing list (or anything similar) and one exclusively for mentors.

I have a feeling that mailing lists are quite an old-fashioned approach for communication. My suggestion is to use https://forums.synfig.org/ for all discussions. We can set-up a private mentors-only category, where only members of particular group can read/post. This will also should encourage all us to give attention to forums (and a good chance to think about their re-structurization).

@ice0 @blackwarthog opinions?

**Comment by morevnaproject** [comment]
> A project will have 2 mentor that's my proposal after viewing what is done in other orgs.

Yes, that's good!

**Comment by reSHARMA** [comment]
> I have a feeling that mailing lists are quite an old-fashioned approach for communication. My suggestion is to use https://forums.synfig.org/ for all discussions. We can set-up a private mentors-only category, where only members of particular group can read/post. This will also should encourage all us to give attention to forums (and a good chance to think about their re-structurization).

Looks good to me, I was just emphasizing to finalize something (irc/forum/mailing list) :)

**Comment by morevnaproject** [comment]
> review requested for the new structure.

Looks good! Just one proposal: to move "GSoC'19" section before "Propose Project" section.

**Comment by reSHARMA** [comment]
@morevnaproject feel free to place it in the appropriate location in index.rst.

**Pull request merged**
